# Based on:-
# * https://ropenscilabs.github.io/actions_sandbox/websites-using-pkgdown-bookdown-and-blogdown.html#action-to-deploy-a-bookdown-site
# * https://github.com/peaceiris/actions-gh-pages
on:
  push:
     branches:
       - master
       - ghptest
  workflow_dispatch:

name: Render development documentation

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            github::gadget-framework/gadgetutils
            github::gadget-framework/gadgetplots
            any::pkgdown
            local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}
        env:
          PKGDOWN_DEV_MODE: devel

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs/dev
          destination_dir: ./${{ github.ref_name }}
